### ISSUE TITLE
Error when not using --progress-only

### ISSUE THREAD

**Issue by Grafikart** [smacke/subsync#2]
When I run the command `subsync video.avi -i unsynced.srt -o sync.srt`, I get this error

```
Traceback (most recent call last):
  File "/usr/local/bin/subsync", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/subsync/subsync.py", line 150, in main
    make_webrtcvad_detector()
  File "/usr/local/lib/python3.7/site-packages/subsync/subsync.py", line 101, in get_speech_segments_from_media
    say('extracting speech segments...', file=sys.stderr)
  File "/usr/local/lib/python3.7/site-packages/subsync/subsync.py", line 24, in say
    print(*args **kwargs)
TypeError: unsupported operand type(s) for ** or pow(): 'tuple' and 'dict'
``` 

But when I use the `--progress-only` flag, everything work as expected.

```
subsync video.avi -i unsynced.srt -o sync.srt --progress-only
7
15
...
```

By the way thanks for this tool, it saved my movie night XD

## Specs

- MacOS 10.14.3
- Python 3.7.2
- ffmpeg version 4.1.1

**Comment by smacke** [comment]
Yikes! Thanks for flagging; 42f95e6 should fix
