### ISSUE TITLE
Error while computing alignments...

### ISSUE THREAD

**Issue by nick-s-b** [smacke/subsync#34]
`Version: subsync 0.2.6`

Hi,
I encountered this error while trying to sync some subs:

````
$ subsync vid.mp4 -i subs.srt -o subs-synced.srt
INFO:subsync.subsync:computing alignments...
Traceback (most recent call last):
  File "/home/opens/.sources/subsync/bin/subsync", line 11, in <module>
    load_entry_point('subsync==0.2.6', 'console_scripts', 'subsync')()
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/subsync/subsync.py", line 63, in main
    srtin_pipe.fit_transform(args.srtin),
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/sklearn/pipeline.py", line 387, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/sklearn/pipeline.py", line 317, in _fit
    **fit_params_steps[name])
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/joblib/memory.py", line 355, in __call__
    return self.func(*args, **kwargs)
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/sklearn/pipeline.py", line 716, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/sklearn/base.py", line 553, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/subsync/subtitle_parsers.py", line 96, in fit
    raise exc
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/subsync/subtitle_parsers.py", line 89, in fit
    max_subtitle_seconds=self.max_subtitle_seconds),
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/subsync/subtitle_parsers.py", line 22, in _srt_parse
    next_sub = next(subs)
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/srt.py", line 342, in parse
    _raise_if_not_contiguous(srt, expected_start, len(srt))
  File "/home/opens/.sources/subsync/lib/python3.7/site-packages/srt.py", line 359, in _raise_if_not_contiguous
    raise SRTParseError(expected_start, actual_start, unmatched_content)
srt.SRTParseError: Expected contiguous start of match or end of input at char 0, but started at char 278494 (unmatched content: 'ÿþ1\x00\r\x00\n\x000\x000\x00:\x000\x005\x00:\x003\x000\x00,\x007\x004\x007\x00 \x00-\x00-\x00>\x00 \x000\x000\x00:\x000\x005\x00:\x003\x003\x00,\x007\x004\x009\x00\r\x00\n\x00[\x00E\x00N\x00G\x00I\x00N\x00E\x00S\x00 \x00R\x00E\x00V\x00]\x00\r\x00\n\x00\r\x00\n\x002\x00\r\x00\n\x000\x000\x00:\x000\x006\x00:\x004\x003\x00,\x002\x007\x007\x00 \x00-\x00-\x00>\x00 \x000\x000\x00:\x000...
````

**Comment by smacke** [comment]
Hi there,

Thanks for filing an issue. This looks like it's probably an encoding problem. This library tries to be semi-intelligent about automatically detecting the file encoding, but sometimes you have to specify it manually, e.g.

`subsync vid.mp4 -i subs.srt -o synced.srt --encoding latin1`

Anyway, my guess is you are trying subs that are encoded in something subsync doesn't know about yet (for when it tries to infer). If you are able, please link to the `subs.srt` file so that I can download and further investigate -- I should be able to give a more definite answer then.

**Comment by nick-s-b** [comment]
@smacke thanks so much! Yes, not specifying the encoding was the issue. The encoding was UTF-16 btw.
Providing the `--encoding utf-16` produced no errors and everything was fine.

Here is the file: https://send.firefox.com/download/f0f97c203a553338/#c4-DHlCuTRcm0hLh5-D63w

**Comment by smacke** [comment]
Yikes -- utf-16 is definitely something that people shouldn't have to be explicit about. Thank you for providing the file! I've added utf-16 to the list of encodings to try out in the hacky "encoding inference" :) so if you upgrade, you shouldn't need to provide it explicitly in the future.
