### ISSUE TITLE
File not found (WinError 2)

### ISSUE THREAD

**Issue by maxlefou** [smacke/subsync#39]
The script doesn't work at all when i'm trying to sync. It gives me this error:
```
INFO:subsync.subsync:computing alignments...
INFO:subsync.speech_transformers:extracting speech segments from subtitles...
Traceback (most recent call last):
  File "C:\Users\*****\AppData\Local\Programs\Python\Python37-32\Scripts\subsync-script.py", line 11, in <module>
    load_entry_point('subsync==0.2.8', 'console_scripts', 'subsync')()
  File "c:\users\*****\appdata\local\programs\python\python37-32\lib\site-packages\subsync\subsync.py", line 73, in main
    reference_pipe.fit_transform(args.reference)
  File "c:\users\*****\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\pipeline.py", line 393, in fit_transform
    return last_step.fit_transform(Xt, y, **fit_params)
  File "c:\users\*****\appdata\local\programs\python\python37-32\lib\site-packages\sklearn\base.py", line 553, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "c:\users\*****\appdata\local\programs\python\python37-32\lib\site-packages\subsync\speech_transformers.py", line 53, in fit
    total_duration = float(ffmpeg.probe(fname)['format']['duration']) - self.start_seconds
  File "c:\users\*****\appdata\local\programs\python\python37-32\lib\site-packages\ffmpeg\_probe.py", line 20, in probe
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "c:\users\*****\appdata\local\programs\python\python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\*****\appdata\local\programs\python\python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable
```
(It's in french, but it says file is not found... Doesn't tell *which* file it's talking about...)

Using Windows 10 and python 3

**Comment by smacke** [comment]
Thanks for filing an issue. Could you include the names of the files and also the command used to invoke the script? Also, what shell are you using?

**Comment by maxlefou** [comment]
`subsync video.mkv -i subs.srt -o subs-timed.srt`

...damnit... I get it, it's because it was an mkv, right?

**Comment by smacke** [comment]
Hmm, I don't think it should matter whether it's an mkv. If you're getting FileNotFoundError, this usually means that it can't find the file in the path you specified. Are you sure `video.mkv` is in the current working directory when you invoked subsync?

**Comment by maxlefou** [comment]
yes. All the files were having the right path.
