### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\ub098' in position 32: ordinal not in range(128)

### ISSUE THREAD

**Issue by pawelduda** [smacke/subsync#6]
Error output:
``` 
➜ subsync S01E01.mp4 -i S01E01.srt > synced.srt
extracting speech segments...
100%|█████████▉| 712.234666667/712.235 [00:02<00:00, 288.16it/s]
...done.
computing alignments...
...done.
auditok (278.0, -871)
webrtcvad (681.0, 69029)
offset seconds: 690.290
Traceback (most recent call last):
  File "/usr/local/bin/subsync", line 11, in <module>
    load_entry_point('subsync==0.1.1', 'console_scripts', 'subsync')()
  File "/usr/local/lib/python2.7/dist-packages/subsync/subsync.py", line 161, in main
    write_offset_file(args.srtin, args.srtout, offset_seconds)
  File "/usr/local/lib/python2.7/dist-packages/subsync/subsync.py", line 42, in write_offset_file
    write_srt_to_file(fwrite, subs)
  File "/usr/local/lib/python2.7/dist-packages/subsync/utils.py", line 61, in write_srt_to_file
    return sys.stdout.write(srt.compose(subs))
UnicodeEncodeError: 'ascii' codec can't encode character u'\ub098' in position 32: ordinal not in range(128)
```

The part of .srt file causing error was:
```
5
00:00:09,750 --> 00:00:11,477
나 잡아봐봐~
("Catch me if you can.")
```

After some hacking I managed to get it to work by adding an env var `PYTHONIOENCODING=utf-8`
```
PYTHONIOENCODING=utf-8 subsync S01E01.mp4 -i S01E01.srt > synced.srt 
```

And it synchronized subs perfectly. Thank you so much for this tool :)

**Comment by smacke** [comment]
Very gratifying that you got some use out of this, and thanks for flagging! Looks like it was an encoding issue when using stdout for output; 940af28 and 244afbb should fix this.

**Comment by MinhyukPark** [comment]
Thanks for the amazing work. I happened to encounter something similar so here's what I did. I don't think too many people are going to run into this issue since it only happened to one out of many files that I've been using it on. I don't need any assistance since I was only having this issue on one file and adding those two lines fixed it but I hope this helps the development and others in case they run into similar issues.

Issue: log below. In my case it wasn't the srt file but the video itself.
Temporary Fix: since i knew my file is utf8 i ended up setting the default encoding manually for just one file
```
// [HOME]/.local/lib/python2.7/site-packages/subsync/subsync.py
import argparse
import logging
import sys
reload(sys) # added
sys.setdefaultencoding('utf8') # added
```

```
INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
INFO:subsync.subsync:computing alignments...
INFO:subsync.speech_transformers:extracting speech segments from subtitles...
INFO:subsync.speech_transformers:extracting speech segments from video [VIDEO TITLE]...
Traceback (most recent call last):
  File "[HOME]/.local/bin/subsync", line 11, in <module>
    load_entry_point('subsync==0.2.3', 'console_scripts', 'subsync')()
  File "[HOME]/.local/lib/python2.7/site-packages/subsync/subsync.py", line 63, in main
    reference_pipe.fit_transform(args.reference)
  File "[HOME]/.local/lib/python2.7/site-packages/sklearn/pipeline.py", line 300, in fit_transform
    return last_step.fit_transform(Xt, y, **fit_params)
  File "[HOME]/.local/lib/python2.7/site-packages/sklearn/base.py", line 464, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "[HOME]/.local/lib/python2.7/site-packages/subsync/speech_transformers.py", line 56, in fit
    ffmpeg.input(fname)
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/_ffmpeg.py", line 32, in input
    return InputNode(input.__name__, kwargs=kwargs).stream()
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/nodes.py", line 173, in __init__
    kwargs=kwargs
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/nodes.py", line 124, in __init__
    super(Node, self).__init__(incoming_edge_map, name, args, kwargs)
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/dag.py", line 119, in __init__
    self.__hash = self.__get_hash()
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/dag.py", line 111, in __get_hash
    hashes = self.__upstream_hashes + [self.__inner_hash]
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/dag.py", line 108, in __inner_hash
    return get_hash(props)
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/_utils.py", line 63, in get_hash
    repr_ = _recursive_repr(item).encode('utf-8')
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/_utils.py", line 55, in _recursive_repr
    kv_pairs = ['{}: {}'.format(_recursive_repr(k), _recursive_repr(item[k])) for k in sorted(item)]
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/_utils.py", line 55, in _recursive_repr
    kv_pairs = ['{}: {}'.format(_recursive_repr(k), _recursive_repr(item[k])) for k in sorted(item)]
  File "[HOME]/.local/lib/python2.7/site-packages/ffmpeg/_utils.py", line 51, in _recursive_repr
    result = str(item)
  File "[HOME]/.local/lib/python2.7/site-packages/future/types/newstr.py", line 102, in __new__
    return super(newstr, cls).__new__(cls, value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 35: ordinal not in range(128)
```

**Comment by smacke** [comment]
Hi @MinhyukPark,

This is interesting. From the traceback, it looks like you are actually experiencing a very different issue from OP's, since this actually looks to be happening in ffmpeg-python.

I'm guessing that your video filename contains non ascii characters, and that this is confusing ffmpeg-python specifically on python 2 unless a default encoding is set.

If you have a moment, could you confirm whether the video filename has non ascii chars?

Best,
Stephen

**Comment by smacke** [comment]
Hi @MinhyukPark,

AFAICT my hypothesis was correct. This should now be fixed if you reinstall (pip install git+https://github.com/smacke/subsync); please let me know if not.

**Comment by MinhyukPark** [comment]
I just tested it as well and changing the filename did the trick. The name of the video file was automatically generated by the same script that named hundreds of other files so I was surprised to find that this is true. Thanks for the quick response! You should definitely come to HackIllinois2020 and do more amazing things.

**Comment by smacke** [comment]
Thank you for the kind words. :) Hopefully I can attend again next year if I still haven't graduated :P
