### ISSUE TITLE
File not found on Windows 10 - [WinError 2]

### ISSUE THREAD

**Issue by danz1995** [smacke/subsync#64]
File not found on Windows 10.

_`C:\Users\dans_\Downloads\test>subsync test.mp4 -i sub1.srt -o o.srt
INFO:subsync.subsync:extracting speech segments from reference 'test.mp4'...
INFO:subsync.speech_transformers:Checking video for subtitles stream...
INFO:subsync.speech_transformers:[WinError 2] The system cannot find the file specified
WARNING:subsync.speech_transformers:[WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "c:\users\dans_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dans_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\dans_\Anaconda3\Scripts\subsync.exe\__main__.py", line 9, in <module>
  File "c:\users\dans_\anaconda3\lib\site-packages\subsync\subsync.py", line 207, in main
    return run(args)
  File "c:\users\dans_\anaconda3\lib\site-packages\subsync\subsync.py", line 81, in run
    reference_pipe.fit(args.reference)
  File "c:\users\dans_\anaconda3\lib\site-packages\sklearn\pipeline.py", line 356, in fit
    self._final_estimator.fit(Xt, y, **fit_params)
  File "c:\users\dans_\anaconda3\lib\site-packages\subsync\speech_transformers.py", line 195, in fit
    process = subprocess.Popen(ffmpeg_args, stdin=None, stdout=subprocess.PIPE, stderr=None)
  File "c:\users\dans_\anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\dans_\anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`_

**Comment by danz1995** [comment]
I was able to figure it out, Windows did not install ffmpeg properly and I had to manually make it a environment variable.

**Comment by smacke** [comment]
Thanks for filing an issue and glad you were able to get it handled. Stay tuned for a graphical version for Windows that contains ffmpeg pre-bundled...

**Comment by danz1995** [comment]
Sure, thank you a lot for this code! I have been using it to sync all movies in my server automatically going through each folder :)
