### ISSUE TITLE
TypeError: '>' not supported between instances of 'Pipeline' and 'Pipeline'

### ISSUE THREAD

**Issue by uduse** [smacke/subsync#71]
**Environment (please complete the following information):**
 - MacOS Mojave
 - Python 3.6.9
 - subsync 0.3.4

**Describe the bug**
```
subsync jp_clean_up_your_room/vid.mp4 -i out.srt -o synced.srt 
INFO:subsync.subsync:extracting speech segments from reference 'jp_clean_up_your_room/vid.mp4'...
INFO:subsync.speech_transformers:Checking video for subtitles stream...
INFO:subsync.speech_transformers:Video file appears to lack subtitle stream
 92%|█████████████████████████████████████████████▎   | 300.0/324.8 [00:00<00:00, 522.67it/s]/Users/Uduse/.local/share/virtualenvs/translations-cyEVysdT/lib/python3.6/site-packages/tqdm/std.py:484: TqdmWarning: clamping frac to range [0, 1]
  charset=Bar.ASCII if ascii is True else ascii or Bar.UTF)
100%|████████████████████████████████████| 324.80072916666666/324.8 [00:00<00:00, 451.65it/s]
INFO:subsync.subsync:...done
INFO:subsync.subsync:extracting speech segments from subtitles 'out.srt'...
INFO:subsync.subtitle_parser:detected encoding: ASCII
INFO:subsync.subsync:...done
INFO:subsync.subsync:computing alignments...
Traceback (most recent call last):
  File "/Users/Uduse/.local/share/virtualenvs/translations-cyEVysdT/bin/subsync", line 8, in <module>
    sys.exit(main())
  File "/Users/Uduse/.local/share/virtualenvs/translations-cyEVysdT/lib/python3.6/site-packages/subsync/subsync.py", line 207, in main
    return run(args)
  File "/Users/Uduse/.local/share/virtualenvs/translations-cyEVysdT/lib/python3.6/site-packages/subsync/subsync.py", line 106, in run
    srt_pipes,
  File "/Users/Uduse/.local/share/virtualenvs/translations-cyEVysdT/lib/python3.6/site-packages/sklearn/base.py", line 574, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/Users/Uduse/.local/share/virtualenvs/translations-cyEVysdT/lib/python3.6/site-packages/subsync/aligners.py", line 77, in transform
    (score, offset), subpipe = max(scores)
TypeError: '>' not supported between instances of 'Pipeline' and 'Pipeline'
```

I tried to track the issue and my guess is that the `subpipes` in `scores` are not comparable. A solution would be using `max(scores, key=lambda x: x[0])` instead of `max(scores)`.

**Comment by smacke** [comment]
@uduse Thank you for the detective work on this -- I believe you are correct. It looks like two different pipelines gave the exact same score / offset pair, leading to this bug. Will push a fix momentarily.

**Comment by smacke** [comment]
@uduse I didn't add a test but I'm pretty confident you already figured out the bug. It should be working now if you upgrade:

```
pip install --upgrade git+https://github.com/smacke/subsync@stable
```

If not, please let me know!
